### ISSUE TITLE
Making Pixel Values of GeoTIFF Images Compatible with HoloDoodler and doodler-engine's Segmentation Model

### ISSUE THREAD

**Issue by venuswku** [dbuscombe-usgs/holodoodler#6]
I encountered the following warning and error while testing HoloDoodler with GeoTIFF files.

## WARNING:param.RGBPlot01329: Clipping input data to the valid range for RGB data ([0..1] for floats or [0..255] for integers).
- When I selected some of my own GeoTIFF files to doodle on, this warning appears for [`2019-06-18-18-57-05_L8_KLAMATH_ms.tif`](https://github.com/Doodleverse/holodoodler/files/9840802/2019-06-18-18-57-05_L8_KLAMATH_ms.tif.zip) and [`another_geotiff.tif`](https://github.com/Doodleverse/holodoodler/files/9840834/another_geotiff.tif.zip).
   - I didn't see this warning when I tested [`examplegeotiff.tif`](https://github.com/Doodleverse/holodoodler/files/9840854/examplegeotiff.tif.zip) from [`./examples/images`](https://github.com/Doodleverse/holodoodler/blob/master/examples/images/examplegeotiff.tif).
- This warning appears for images with pixel values that are outside of the accepted range for displaying the image in HoloViews' RGB plot ([0..1] for floats or [0..255] for integers).
   - For each tested image, I printed out their corresponding numpy array and other information (shape, data type, contains NaN):
      - `2019-06-18-18-57-05_L8_KLAMATH_ms.tif`
         - I could view this image in HoloDoodler but the warning appeared in the terminal. When I doodled on it and tried to compute its segmentation, an error occurred (mentioned below).
         - ```
           numpy array shape (rows, columns, bands): (177, 126, 6)
           numpy array data type: float32
           numpy array contains a NaN value: False
           numpy array contains a +/- infinity value: True
           numpy array:
           [[[          -inf           -inf           -inf           -inf           -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf           -inf 0.00000000e+00]
             [1.37962356e-01 1.19247392e-01 1.13302633e-01 1.40846670e-01  1.64097264e-01 2.80000000e+03]
             ...
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]]

            [[          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [1.49763808e-01 1.36729375e-01 1.28186539e-01 1.34241387e-01  1.40626490e-01 2.80000000e+03]
             ...
             [8.26321021e-02 6.95096031e-02 4.21196893e-02 3.29779804e-01  1.08106479e-01 2.72000000e+03]
             [8.04523528e-02 6.99059218e-02 4.05344218e-02 3.39467555e-01  1.25412315e-01 2.72000000e+03]
             [7.72818178e-02 5.60568385e-02 3.30704525e-02 2.07758188e-01  6.58546761e-02 2.72000000e+03]]

            ...

            [[          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             ...
             [8.59127194e-02 8.26100782e-02 5.98658882e-02 3.47349852e-01  1.46086857e-01 2.72000000e+03]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]
             [          -inf           -inf           -inf           -inf            -inf 0.00000000e+00]]]
           ```
      - `another_geotiff.tif`
         - I couldn't see this image at all. It was just a blank plot so I decided to not doodle or segment it. The warning also appeared in the terminal for this image.
            ![cannot_view_another_geotiff_on_holodoodler](https://user-images.githubusercontent.com/71415129/197250658-7f19c19e-31ae-4106-8a50-f55a14f26105.jpg)
         - ```
           numpy array shape (rows, columns, bands): (1001, 1001, 3)
           numpy array data type: uint16
           numpy array contains a NaN value: False
           numpy array contains a +/- infinity value: False
           numpy array:
           [[[   0    0    0]
             [ 799  555  330]
             [ 788  546  322]
             ...
             [1061 1106  823]
             [1433 1353 1263]
             [2430 2280 2408]]

            [[   0    0    0]
             [ 774  534  304]
             [ 792  533  313]
             ...
             [1027 1074  771]
             [1125 1154  859]
             [1733 1650 1492]]

            ...

            [[   0    0    0]
             [   0    0    0]
             [   0    0    0]
             ...
             [   0    0    0]
             [   0    0    0]
             [   0    0    0]]]
           ```
      - `examplegeotiff.tif`
         - This is the only image that had pixel values within the range so no warning appeared for this image.
         - ```
           numpy array shape (rows, columns, bands): (400, 500, 3)
           numpy array data type: uint8
           numpy array contains a NaN value: False
           numpy array contains a +/- infinity value: False
           numpy array:
           [[[ 86  82  81]
             [ 87  83  82]
             [ 82  80  78]
             ...
             [ 73  70  63]
             [ 66  72  58]
             [ 88  88  81]]

            [[ 89  86  85]
             [ 87  85  84]
             [ 81  78  78]
             ...
             [ 75  74  66]
             [ 75  76  67]
             [ 82  83  73]]

            ...

            [[156 159 153]
             [164 166 160]
             [136 140 128]
             ...
             [160 158 156]
             [158 155 153]
             [156 151 148]]]
           ```
- I placed the following block of code in `./doodler/components.py`'s [`_load_image()`](https://github.com/Doodleverse/holodoodler/blob/master/doodler/components.py#:~:text=%40param.depends(%27location,%3D(w%20/%20h))) function to scale input images' pixel values, but I'm not sure if this is the best way. **Is there a better way to scale image pixel values?**
   ```python
   # Make sure image array is within the range [0, 255] for integers or [0, 1] for floats.
   if np.issubdtype(img.dtype, np.integer) and not (np.all(img >= 0) and np.all(img <= 255)):
       min_pixel_val, max_pixel_val = np.min(img), np.max(img)
       img = (np.rint(((img - min_pixel_val) / (max_pixel_val - min_pixel_val)) * 255)).astype(np.uint8)
   elif np.issubdtype(img.dtype, np.floating) and not (np.all(img >= 0) and np.all(img <= 1)):
       # Infinity can only be represented as a float as of right now, so we don't need the following two lines for scaling integers.
       img[img == float("-inf")] = float(0)
       img[img == float("inf")] = float(1)
       # Get the minimum and maximim pixel values after removing the +/- infinity values.
       min_pixel_val, max_pixel_val = np.min(img), np.max(img)
       img = (img - min_pixel_val) / (max_pixel_val - min_pixel_val)
   ```
   - After adding this block of code, I was finally able to see `another_geotiff.tif` in HoloDoodler and the warning never appeared again for any input image.
      ![can_view_another_geotiff_on_holodoodler_after_scaling_pixel_values](https://user-images.githubusercontent.com/71415129/197262206-45bc6421-c1ba-4745-b7c6-c8c274d969ee.jpg)
   - I added `img[img == float("-inf")] = 0` and `img[img == float("inf")] = 1` to scale +/- infinity values because doing any math operation on infinity will always result in infinity (for Python).

## ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
- I only encountered this error when I clicked on the button for computing `2019-06-18-18-57-05_L8_KLAMATH_ms.tif`'s segmentation. Segmentation worked for `examplegeotiff.tif` and `another_geotiff.tif` (after its pixel values were scaled and I could see the image in HoloDoodler).
   - If you look at the data type of the numpy array values for `2019-06-18-18-57-05_L8_KLAMATH_ms.tif` after scaling, it contains 32-bit floats, which are smaller/takes up less memory than 64-bit floats. I checked and made sure there are no +/- infinity or NaN values in the array after scaling, so I'm not too sure what caused this error.
   - `2019-06-18-18-57-05_L8_KLAMATH_ms.tif` after scaling
      ```
      numpy array shape (rows, columns, bands): (177, 126, 6)
      numpy array data type: float32
      numpy array contains a NaN value: False
      numpy array contains a +/- infinity value: False
      numpy array:
      [[[0.         0.         0.        ]
        [0.         0.         0.        ]
        [0.28475344 0.24612588 0.23385593]
        ...
        [0.         0.         0.        ]
        [0.         0.         0.        ]
        [0.         0.         0.        ]]

       [[0.         0.         0.        ]
        [0.         0.         0.        ]
        [0.30911157 0.2822086  0.26457623]
        ...
        [0.17055215 0.1434674  0.08693478]
        [0.16605316 0.1442854  0.08366279]
        [0.1595092  0.11570097 0.06825721]]

       ...

       [[0.         0.         0.        ]
        [0.         0.         0.        ]
        [0.         0.         0.        ]
        ...
        [0.17732333 0.17050669 0.12356282]
        [0.         0.         0.        ]
        [0.         0.         0.        ]]]
      ```
   - `another_geotiff.tif` after scaling
      ```
      numpy array shape (rows, columns, bands): (177, 126, 6)
      numpy array data type: unit8
      numpy array contains a NaN value: False
      numpy array contains a +/- infinity value: False
      numpy array:
      [[[ 0  0  0]
        [17 12  7]
        [17 11  7]
        ...
        [23 24 18]
        [31 29 27]
        [53 49 52]]

       [[ 0  0  0]
        [16 11  6]
        [17 11  6]
        ...
        [22 23 16]
        [24 25 18]
        [37 36 32]]

       ...

       [[ 0  0  0]
        [ 0  0  0]
        [ 0  0  0]
        ...
        [ 0  0  0]
        [ 0  0  0]
        [ 0  0  0]]]
      ```
   - `examplegeotiff.tif` after scaling
      ```
      numpy array shape (rows, columns, bands): (177, 126, 6)
      numpy array data type: unit8
      numpy array contains a NaN value: False
      numpy array contains a +/- infinity value: False
      numpy array:
      [[[ 86  82  81]
        [ 87  83  82]
        [ 82  80  78]
        ...
        [ 73  70  63]
        [ 66  72  58]
        [ 88  88  81]]

       [[ 89  86  85]
        [ 87  85  84]
        [ 81  78  78]
        ...
        [ 75  74  66]
        [ 75  76  67]
        [ 82  83  73]]

       ...

       [[156 159 153]
        [164 166 160]
        [136 140 128]
        ...
        [160 158 156]
        [158 155 153]
        [156 151 148]]]
      ```
- I faintly remember @dbuscombe-usgs mentioning that the segmentation model only takes in 8-bit integers, so I tried converting the values into 8-bit integers (and even 64-bit floats) but the same error appeared.
   - Code for converting the float values into 8-bit integers:
      ```python
      elif np.issubdtype(img.dtype, np.floating) and not (np.all(img >= 0) and np.all(img <= 1)):
            # Infinity can only be represented as a float as of right now, so we don't need the following two lines for scaling integers.
            img[img == float("-inf")] = 0
            img[img == float("inf")] = 255
            # Get the minimum and maximim pixel values after removing the +/- infinity values.
            min_pixel_val, max_pixel_val = np.min(img), np.max(img)
            img = (img - min_pixel_val) / (max_pixel_val - min_pixel_val).astype(np.uint8)
      ```
   - Code for converting float values into 64-bit floats:
      ```python
      elif np.issubdtype(img.dtype, np.floating) and not (np.all(img >= 0) and np.all(img <= 1)):
            # Infinity can only be represented as a float as of right now, so we don't need the following two lines for scaling integers.
            img[img == float("-inf")] = float(0)
            img[img == float("inf")] = float(1)
            # Get the minimum and maximim pixel values after removing the +/- infinity values.
            min_pixel_val, max_pixel_val = np.min(img), np.max(img)
            img = (img - min_pixel_val) / (max_pixel_val - min_pixel_val).astype(np.float64)
      ```
- Full error message:
```
error: ValueError("Input contains NaN, infinity or a value too large for dtype('float64').")
Traceback (most recent call last):
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\server\protocol_handler.py", line 97, in handle
    work = await handler(message, connection)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\server\session.py", line 95, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\server\session.py", line 289, in _handle_patch
    message.apply_to_document(self.document, self)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 115, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_json(self, event_json, references, setter)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\events.py", line 259, in handle_json
    handler(doc, event_json, references, setter)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\events.py", line 300, in _handle_json
    cb(event_json["msg_data"])
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\callbacks.py", line 355, in trigger_json_event
    model._trigger_event(event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\util\callback_manager.py", line 119, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\callbacks.py", line 247, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\document\callbacks.py", line 408, in invoke_with_curdoc
    return f()
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\bokeh\util\callback_manager.py", line 115, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\reactive.py", line 428, in _server_event
    self._comm_event(doc, event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\reactive.py", line 415, in _comm_event
    state._handle_exception(e)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\io\state.py", line 391, in _handle_exception
    raise exception
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\reactive.py", line 413, in _comm_event
    self._process_bokeh_event(doc, event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\reactive.py", line 350, in _process_bokeh_event
    self._process_event(event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\widgets\button.py", line 184, in _process_event
    self.clicks += 1
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 367, in _f
    instance_param.__set__(obj, val)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\__init__.py", line 625, in __set__
    super(Dynamic,self).__set__(obj,val)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 369, in _f
    return f(self, obj, val)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 1248, in __set__
    obj.param._call_watcher(watcher, event)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 2039, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\panel\param.py", line 502, in event
    self.object.param.trigger(p_name)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 1989, in trigger
    self_.set_param(**dict(params, **triggers))
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 1925, in set_param
    return self_.update(kwargs)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 1898, in update
    self_._batch_call_watchers()
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 2059, in _batch_call_watchers
    self_._execute_watcher(watcher, events)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 2021, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 669, in caller
    return function()
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\param\parameterized.py", line 407, in _depends
    return func(*args, **kw)
  File "C:\Users\Venuxk\Projects\holodoodler\doodler\components.py", line 610, in _compute_segmentation
    sigma_max = self.settings.as_dict()['sigma_max']
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\doodler_engine\image_segmentation.py", line 487, in segmentation
    result, unique_labels = do_classify(img,mask,n_sigmas,multichannel,intensity,edges,texture, sigma_min,sigma_max, rf_downsample_value)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\doodler_engine\image_segmentation.py", line 420, in do_classify
    clf.fit(training_data, training_labels)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\pipeline.py", line 394, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 752, in fit
    return self._fit(X, y, incremental=False)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 393, in _fit
    X, y = self._validate_input(X, y, incremental, reset=first_pass)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py", line 1106, in _validate_input
    reset=reset,
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\utils\validation.py", line 976, in check_X_y
    estimator=estimator,
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\utils\validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "C:\Users\Venuxk\anaconda3\envs\holodoodler-dev37\lib\site-packages\sklearn\utils\validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by ddbuscombe** [comment]
Thanks for the detailed issue

Perhaps imagery should always be scaled to 8-bit (the way you implemented that seesm fine) and its `dtype` should be updated using `.astype(np.uint8)`

Basically, what you have done, but without the option for imagery to be 16-bit, 32-bit or 64-bit

If that happens, does the error message go away?

**Comment by venuswku** [comment]
Yes, the error message goes away if I only test HoloDoodler with imagery that are 8-bit. It works for `another_geotiff.tif` though (mentioned above), which is 16-bits, so I dug a little deeper out of curiosity.

**Turns out that data type or bit size was not the cause of the value error! It was the image array that was passed into `sklearn`'s validation function.**

In `_compute_segmentation()` from `.\doodler\components.py`, `self.input_image.array` is passed into `doodler-engine`'s `segmentation()` function:
```python
self._segmentation = segmentation(
    img=self.input_image.array,
    mask=self._mask_doodles,
    crf_theta_slider_value=self.settings.as_dict()['crf_theta'],
    crf_mu_slider_value = self.settings.as_dict()['crf_mu'],
    rf_downsample_value = self.settings.as_dict()['rf_downsample_value'],
    crf_downsample_factor = self.settings.as_dict()['crf_downsample_factor'],
    n_sigmas = self.settings.as_dict()['n_sigmas'],
    multichannel = self.settings.as_dict()['multichannel'],
    intensity = self.settings.as_dict()['intensity'],
    edges = self.settings.as_dict()['edges'],
    texture = self.settings.as_dict()['texture'],
    sigma_min = self.settings.as_dict()['sigma_min'],
    sigma_max = self.settings.as_dict()['sigma_max']
)
```
This image array is eventually passed as an argument into `_assert_all_finite()` in `sklearn\utils\validation.py`, where the value error is raised:
```python
def _assert_all_finite(X, allow_nan=False, msg_dtype=None):
    """Like assert_all_finite, but only for ndarray."""
    # validation is also imported in extmath
    from .extmath import _safe_accumulator_op

    if _get_config()["assume_finite"]:
        return
    X = np.asanyarray(X)
    # First try an O(n) time, O(1) space solution for the common case that
    # everything is finite; fall back to O(n) space np.isfinite to prevent
    # false positives from overflow in sum method. The sum is also calculated
    # safely to reduce dtype induced overflows.
    is_float = X.dtype.kind in "fc"
    if is_float and (np.isfinite(_safe_accumulator_op(np.sum, X))):
        pass
    elif is_float:
        msg_err = "Input contains {} or a value too large for {!r}."
        if (
            allow_nan
            and np.isinf(X).any()
            or not allow_nan
            and not np.isfinite(X).all()
        ):
            type_err = "infinity" if allow_nan else "NaN, infinity"
            raise ValueError(
                msg_err.format(
                    type_err, msg_dtype if msg_dtype is not None else X.dtype
                )
            )
    # for object dtype data, we only check for NaNs (GH-13254)
    elif X.dtype == np.dtype("object") and not allow_nan:
        if _object_dtype_isnan(X).any():
            raise ValueError("Input contains NaN")
```
I looked for where `self.array` was assigned in the `InputImage` class and realized that the scaled pixels array was never used for segmentation. The original image array (without scaling) for `2019-06-18-18-57-05_L8_KLAMATH_ms.tif` contains some negative infinity values, causing the value error to be raised. `self.array` was already assigned to the original image array before I scaled the pixels:
```python
@param.depends('location', watch=True)
def _load_image(self):
    if not self.location:
        self._plot = self._pane.object = hv.RGB(data=[])
        return
    self.array = array = self.read_from_fs(self.location)     # self.array was assigned here!
        
    # this is where we want to split the image array used for doodling
    # and the n-band array for segmentation
    if np.ndim(array) <=2:
        array = np.dstack((array,array,array))
        
    h, w, nbands = array.shape
    if nbands > 3:
        img = array[:, :, 0:3].copy()
    else:
        img = array.copy()

    # Make sure image array is within the range
    # [0, 255] for integers or [0, 1] for floats.
    if np.issubdtype(img.dtype, np.integer) and not (np.all(img >= 0) and np.all(img <= 255)):
        img = (img / np.amax(img) * 255).astype(np.uint8)
    elif np.issubdtype(img.dtype, np.floating) and not (np.all(img >= 0) and np.all(img <= 1)):
        # Infinity can only be represented as a float as of right now,
        # so we don't need the following two lines for scaling integers.
        img[img == float("-inf")] = float(0)
        img[img == float("inf")] = float(1)
        img = img / np.amax(img)

    # Preserve the aspect ratio
    self.img_bounds = (0, 0, w, h)
    self._plot = self._pane.object = hv.RGB(
        img, bounds=self.img_bounds
    ).opts(aspect=(w / h))
```
So I just simply assigned `self.array` after the pixel values were scaled. I even removed the `.astype(np.uint8)` code and segmentation still works for `another_geotiff.tif`. Looks like I didn't need to convert the pixel values into 8-bit integers for the image to be segmented. **Should I still convert the scaled pixel values into `np.uint8` just in case?**
```python
@param.depends('location', watch=True)
def _load_image(self):
    if not self.location:
        self._plot = self._pane.object = hv.RGB(data=[])
        return
    array = self.read_from_fs(self.location)
        
    # Create image with 3 bands for images with 2 or less bands.
    if np.ndim(array) <= 2:
        array = np.dstack((array,array,array))
        
    # Split the image array used for doodling and the n-band array for segmentation.
    h, w, nbands = array.shape
    if nbands > 3:
        img = array[:, :, 0:3].copy()
    else:
        img = array.copy()

    # Make sure image array is within the range
    # [0, 255] for integers or [0, 1] for floats.
    if np.issubdtype(img.dtype, np.integer) and not (np.all(img >= 0) and np.all(img <= 255)):
        # Convert the division results back to integers because division creates float results.
        img = (np.rint(img / np.amax(img) * 255)).astype(int)
    elif np.issubdtype(img.dtype, np.floating) and not (np.all(img >= 0) and np.all(img <= 1)):
        # Infinity can only be represented as a float as of right now,
        # so we don't need the following two lines for scaling integers.
        img[img == float("-inf")] = float(0)
        img[img == float("inf")] = float(1)
        img = (img / np.amax(img))
        
    # Set self.array after its pixel values have been scaled to the expected range.
    self.array = img

    # Preserve the aspect ratio.
    self.img_bounds = (0, 0, w, h)
    self._plot = self._pane.object = hv.RGB(
        img, bounds=self.img_bounds
    ).opts(aspect=(w / h))
```

Segmenting [`2019-06-18-18-57-05_L8_KLAMATH_ms.tif`](https://github.com/Doodleverse/holodoodler/files/9855773/2019-06-18-18-57-05_L8_KLAMATH_ms.tif.zip) (float32) works with no value errors now!
![float32_input_on_leafmap](https://user-images.githubusercontent.com/71415129/197643270-152ab8fc-8794-48af-ba07-c52b548319ee.jpg)
Here are my results: [20221024-141517.zip](https://github.com/Doodleverse/holodoodler/files/9855743/20221024-141517.zip). Sorry, the segmentation is a bit off this time too because the image is so dark. I just realized the part where I marked water is actually land now that I see it on a map. Here are the image outputs in `leafmap`:
- `2019-06-18-18-57-05_L8_KLAMATH_ms_colorlabel.tif`
  ![colorlabel_on_leafmap](https://user-images.githubusercontent.com/71415129/197643290-92888bd9-2031-42dd-9a58-8e5216af4e42.jpg)
- `2019-06-18-18-57-05_L8_KLAMATH_ms_doodles.tif`
  ![doodles_on_leafmap](https://user-images.githubusercontent.com/71415129/197643318-3f4fb104-b00b-4a5f-94aa-70f5a12de266.jpg)
- `2019-06-18-18-57-05_L8_KLAMATH_ms_label.tif`
  ![label_on_leafmap](https://user-images.githubusercontent.com/71415129/197643341-6421837f-52d3-4c4c-87d9-7091f14d81b8.jpg)

**Comment by ddbuscombe** [comment]
Looks great! Thanks for digging further!

`Should I still convert the scaled pixel values into np.uint8 just in case?`

Perhaps doodle a 16-bit and a 32-bit input image, and if they work well, no need to assert a dtype of np.uint8

**Comment by venuswku** [comment]
I tested with `2019-06-18-18-57-05_L8_KLAMATH_ms.tif` (float32) from above, [2021-10-29-18-57-40_L8_KLAMATH_ms.tif](https://github.com/Doodleverse/holodoodler/files/9855920/2021-10-29-18-57-40_L8_KLAMATH_ms.tif.zip) (float32), and `another_geotiff.tif` (uint16) from above. All 8-bit and 32-bit GeoTIFFs could be doodled and labeled so far, but I would like to test with some more images! How do I get 16-bit imagery? I read that Landsat 8-9 are 16-bit, but I'm struggling to download those satellite images.

Edit: Thanks to Dan's suggestion, I'm looking into converting the 32-bit images into 16-bit images with `gdal` or `rasterio`. Once I can confirm that my fix can scale 16-bit images, then my pull request can be merged.

**Comment by venuswku** [comment]
So I tried converting 32-bit (float) GeoTIFFs into 16-bit (unsigned integer) GeoTIFFs with GDAL's Python API:
```python
from osgeo import gdal

input_file = "examples/images/2019-12-27-18-57-29_L8_KLAMATH_ms.tif"
input_dataset = gdal.Open(input_file)
total_bands = input_dataset.RasterCount
driver = gdal.GetDriverByName("GTiff")
output_dataset = driver.Create(
    "examples/images/16BIT_2019-12-27-18-57-29_L8_KLAMATH_ms.tif",
    xsize = input_dataset.RasterXSize,
    ysize = input_dataset.RasterYSize,
    bands = total_bands,
    eType = gdal.GDT_UInt16
)
output_dataset.SetProjection(input_dataset.GetProjection())
output_dataset.SetGeoTransform(input_dataset.GetGeoTransform())
for i in range(total_bands):
    input_band = input_dataset.GetRasterBand(i+1)
    arr = input_band.ReadAsArray()
    output_band = output_dataset.GetRasterBand(i+1)
    output_band.WriteArray(arr)
output_band.FlushCache()
input_dataset = None
output_dataset = None
```
and [GDAL's command line](https://gdal.org/programs/gdal_translate.html):
```python
gdal_translate -ot UInt16 -if GTiff -of GTiff "C:/Users/Venus/holodoodler/examples/images/2019-12-27-18-57-29_L8_KLAMATH_ms.tif" "C:/Users/Venus/holodoodler/examples/images/16BIT_2019-12-27-18-57-29_L8_KLAMATH_ms.tif"
```
but both ways outputted completely dark images ([example output image](https://github.com/Doodleverse/holodoodler/files/10230708/16BIT_2019-12-27-18-57-29_L8_KLAMATH_ms.zip)), which are hard to segment. I remember reading a StackOverflow post saying that the image might be very dark if the pixel values are too big so that might be why the outputted images are hard to see. **I'm not too familiar with GDAL though so please correct me if I used it wrong!**

Instead of converting `float32` GeoTIFFs, I slightly modified a [GDAL script](https://stackoverflow.com/a/33950009) to create my own segmentable `uint16` and `float64` GeoTIFFs. An example script is shown below:
```python
from osgeo import gdal, osr

# Initialize the Image Size
image_size = (500,500)
# Choose some Geographic Transform (Around Lake Tahoe)
lat = [39,38.5]
lon = [-120,-119.5]
# Create Each Channel
r_pixels = np.zeros((image_size), dtype=np.uint16)
g_pixels = np.zeros((image_size), dtype=np.uint16)
b_pixels = np.zeros((image_size), dtype=np.uint16)
# Set the Pixel Data (Create some boxes)
for x in range(0,image_size[0]):
    for y in range(0,image_size[1]):
        if x < image_size[0]/2 and y < image_size[1]/2:
            r_pixels[y,x] = 3000
        elif x >= image_size[0]/2 and y < image_size[1]/2:
            g_pixels[y,x] = 2150
        elif x < image_size[0]/2 and y >= image_size[1]/2:
            b_pixels[y,x] = 3894
        else:
            r_pixels[y,x] = 9038
            g_pixels[y,x] = 5843
            b_pixels[y,x] = 2954
# Set Geotransform
nx = image_size[0]
ny = image_size[1]
xmin, ymin, xmax, ymax = [min(lon), min(lat), max(lon), max(lat)]
xres = (xmax - xmin) / float(nx)
yres = (ymax - ymin) / float(ny)
geotransform = (xmin, xres, 0, ymax, 0, -yres)
# Create the 3-band Raster File
dst_ds = gdal.GetDriverByName('GTiff').Create('examples/images/custom_16_bit.tif', ny, nx, 3, gdal.GDT_UInt16)
dst_ds.SetGeoTransform(geotransform)    # specify coords
srs = osr.SpatialReference()            # establish encoding
srs.ImportFromEPSG(3857)                # WGS84 lat/long
dst_ds.SetProjection(srs.ExportToWkt()) # export coords to file
dst_ds.GetRasterBand(1).WriteArray(r_pixels)   # write r-band to the raster
dst_ds.GetRasterBand(2).WriteArray(g_pixels)   # write g-band to the raster
dst_ds.GetRasterBand(3).WriteArray(b_pixels)   # write b-band to the raster
dst_ds.FlushCache()                     # write to disk
dst_ds = None
```
Compared to dark images, the outputted image of the above script is easier to segment:
![custom_16_bit_geotiff](https://user-images.githubusercontent.com/71415129/207684192-b1d4cb1a-c992-4b6b-83c0-1e990db727b9.jpg)
I was able to doodle and segment the outputted images from this script. This means my scaling fix works for images in the most common numerical data types (`uint8`, `uint16`, `float32`, `float64`). My PR can be merged!

**Comment by ddbuscombe** [comment]
Excellent stuff!
